const CommonConst = {
    LV_USvrKey: "LV_USvrKey:",
    VN: "VN",
    EN: "EN",
    FormatDD: "DD",
    FormatDDMM: "DD/MM",
    FormatDate: "dd/MM/yyyy",
    FormatSQLDate: "YYYY/MM/DD",
    ModeTime: "time",
    FormatHHmm: "HH:mm",
    FormatHmm: "H:mm",
    FormatHHmmss: "HH:mm:ss",
    OfflinePage: "offline.html",
    google: "google",

    Customers: {
        Default: "LVHCS",
        TienThu: "TienThu"
    },

    SCENE: {
        LeaveRequest: "LeaveRequest",
        CreateLeaveRequest: "CreateLeaveRequest",
        BusinessTripRequest: "BusinessTripRequest",
        CreateBusinessTripRequest: "CreateBusinessTripRequest",
        DetailBusinessTripRequest: "DetailBusinessTripRequest",
        BusinessTripApprove: "BusinessTripApprove",
        DetailBusinessTripApprove: "DetailBusinessTripApprove",
        DetailLeaveRequest: "DetailLeaveRequest",
        LeaveApprove: "LeaveApprove",
        DetailLeaveApprove: "DetailLeaveApprove",
        OTRequest: "OTRequest",
        CreateOTRequest: "CreateOTRequest",
        DetailOTRequest: "DetailOTRequest",
        OTApprove: "OTApprove",
        DetailOTApprove: "DetailOTApprove",
        OTGroupApprove: "OTGroupApprove",
        DetailOTGroupApprove: "DetailOTGroupApprove",
        OTGroupRequest: "OTGroupRequest",
        CreateOTGroupRequest: "CreateOTGroupRequest",
        OTGroupItemEdit: "OTGroupItemEdit",
        DetailOTGroupRequest: "DetailOTGroupRequest",
        OTGroupApprove: "OTGroupApprove",
        DetailOTGroupApprove: "DetailOTGroupApprove",
        Login: "Login",
        ChangePassword: "ChangePassword",
        HomePage: "HomePage",
        MyOffline: "MyOffline",
        CheckInQRCode: "CheckInQRCode",
        CheckInOut: "CheckInOut",
        MyProfile: "MyProfile",
        MyTeam: "MyTeam",
        EmployeeDirectory: "EmployeeDirectory",
        Manager: "Manager",
        EmployeeItem: "EmployeeItem",
        Chat: "Chat",
        CheckInOutHistory: "CheckInOutHistory",
        EmployeeCamera: "EmployeeCamera",
        EmployeeProfile: "EmployeeProfile",
        News: "News",
        NewsDetail: "NewsDetail",
        Events: "Events",
        Policy: "Policy",
        MyTimesheet: "MyTimesheet",
        MissingInOutRequest: "MissingInOutRequest",
        MissingRequestCreate: "MissingRequestCreate",
        MissingRequestDetail: "MissingRequestDetail",
        MyPaystub: "MyPaystub",
        ChatIndex: "ChatIndex",
        Chat: "Chat",
        MissingInOutApprove: "MissingInOutApprove",
        MissingApproveDetail: "MissingApproveDetail",
        EmployeeAttendance: "EmployeeAttendance",
        LateEarlyRequest: "LateEarlyRequest",
        LateEarlyRequestDetail: "LateEarlyRequestDetail",
        LateEarlyRequestCreate: "LateEarlyRequestCreate",
        LateEarlyApprove: "LateEarlyApprove",
        LateEarlyApproveDetail: "LateEarlyApproveDetail",

        ExtraDayOffRequest: "ExtraDayOffRequest",
        DetailExtraDayOffRequest: "DetailExtraDayOffRequest",
        CreateExtraDayOffRequest: "CreateExtraDayOffRequest",
        ExtraDayOffApprove: "ExtraDayOffApprove",
        DetailExtraDayOffApprove: "DetailExtraDayOffApprove",

        ExtraWorkDayRequest: "ExtraWorkDayRequest",
        DetailExtraWorkDayRequest: "DetailExtraWorkDayRequest",
        CreateExtraWorkDayRequest: "CreateExtraWorkDayRequest",
        DetailExtraWorkDayApprove: "DetailExtraWorkDayApprove",
        ExtraWorkDayApprove: "ExtraWorkDayApprove",

        QuestionAnswer: "QuestionAnswer",
        NewRecruit: "NewRecruit",
        NowAvailable: "NowAvailable",
        Missing: "Missing",
        Resign: "Resign",
        Appoint: "Appoint",
        ReportDetail: "ReportDetail",
        ListNotification: "ListNotification",
        NotificationDetails: "NotificationDetails",
        Authorization: "Authorization",
        AuthorizationCreate: "AuthorizationCreate",
        AuthorizationDetail: "AuthorizationDetail",
        CheckInOutGPSDetail: "CheckInOutGPSDetail",
        CheckInOutNetwork: "CheckInOutNetwork",
        Read: "Read"
    },

    TAB: {
        Employee: "employee",
        Myteam: "myteam",
        Office: "office",
        PostNew: "PostNew",
        CnB: "cnb",
        Recruitment: "recruitment",
        Evaluate: "evaluate",
        Training: "training",
        Info: "Info",
        MyTimesheet: "MyTimesheet",
        News: {
            TTC: "news41",
            NNNC: "news42",
            NVHN: "news43",
            QTNS: "news44",
            DGNV: "news45",
            DTTT: "news46",
        },
        Events: {
            TTC: "events41",
            NNNC: "events42",
            NVHN: "events43",
            QTNS: "events44",
            DGNV: "events45",
            DTTT: "events46",
        },
        Policy: {
            TTC: "hrpolicy41",
            NNNC: "atspolicy42",
            NVHN: "hrpolicy43",
            QTNS: "cnbpolicy44",
            DGNV: "perfpolicy45",
            DTTT: "lmspolicy46",
        },
        Manager: {
            EmployeeInfo: "employeeinfo",
            PaySlip: "payslip"
        },
        QA: {
            Question: "question",
            Answer: "answer"
        },
        Timesheet: {
            Working: "working",
            InOut: "inout",
        },
        MyTeamTab: {
            DirectManagement: "DirectManagement",
            IndirectManagement: "IndirectManagement"
        },
    },

    VALUE_LIST: {
        LStatus: "LStatus",
        LeavePeriod: "HCSEM_EmpDayOff.LeavePeriod",
        BusinessTripPeriod: "HCSEM_EmpDayTrip.BusinessTripPeriod",
        BusinessTripVehicle: "HCSHP_BusinessTripRequest.Vehicle",
        items: "items"
    },

    KEY: {
        OutputParams: "OutputParams",
        TotalItems: "TotalItems",
        TotalPages: "TotalPages",
        PrimaryKey: "PrimaryKey",
        DisplayColumn: "DisplayColumn",
        IsChecked: "IsChecked",
        FilterText: "FilterText",
        PageIndex: "PageIndex",
        PageSize: "PageSize",
        Color: "Color",
        DateFormat: "DateFormat",
        DayString: "DayString",
        IsAutoLogout: "IsAutoLogout",
        AutoLogoutTime: "AutoLogoutTime",
        PhotoUrl: "PhotoUrl",
        PRDateFormat: "PRDateFormat",
        FirstDateLeaveItem: "FirstDateLeaveItem",
        LastDateLeaveItem: "LastDateLeaveItem",
        Language: "Language",
        ID: "ID",
        id: "id",
        parentId: "parentId",
        name: "name",
        children: "children",
        TotalReply: "TotalReply",
        GroupID: "GroupID",
        Subject: "Subject",
        Content: "Content",
        ReplyContent: "ReplyContent",
        QuoteContent: "QuoteContent",
        DepartmentName: "DepartmentName",
        DepartmentCode: "DepartmentCode",
        ParentCode: "ParentCode",
        data: "data",
        Data: "Data",
        title: "title",
        body: "body",
        Body: "Body",
        UserID: "UserID",
        EmployeeCode: "EmployeeCode",
        IsApprove: "IsApprove",
        screen: "screen",
        icon: "icon",
        Icon: "Icon",
        DefaultName: "DefaultName",
        Theme: "Theme",
        Images: "Images",
        Status: "Status",
        status: "status",
        Caption: "Caption",
        Value: "Value",
        IsMultiChecked: "IsMultiChecked",
        MultiSelectedItems: "MultiSelectedItems",
        MultiSelectedItemsName: "MultiSelectedItemsName",
        SL: "SL",
        ProcessID: "ProcessID",
        FunctionList: "FunctionList",
        FunctionGroupList: "FunctionGroupList",
        FunctionID: "FunctionID",
        Url: "Url",
        RecID: "RecID",
        RecordID: "RecordID",
        Index: "Index",
        EmpNum: "EmpNum",
        ExpoPushData: "ExpoPushData",
        details: "details",
        ssid: "ssid",
        bssid: "bssid",
        longitude: "longitude",
        latitude: "latitude",
        Lat: "Lat",
        Lng: "Lng",
        Type: "Type",
        description: "description",
        Time: "Time",
        Date: "Date",
        ipAddress: "ipAddress"


    },

    FUNCTION: {
        LeaveRequest: "Mobi.007",
        LeaveApprove: "Mobi.008",
        OTRequest: "Mobi.012",
        OTApprove: "Mobi.013",
        OTGroupRequest: "Mobi.015",
        OTGroupApprove: "Mobi.016",
        MissingInOutRequest: "Mobi.014",
        MissingInOutApprove: "Mobi.017",
        BusinessTripRequest: "Mobi.019",
        BusinessTripApprove: "Mobi.020",
        LateEarlyRequest: "Mobi.021",
        LateEarlyApprove: "Mobi.022",
        ExtraDayOffRequest: "Mobi.023",
        ExtraDayOffApprove: "Mobi.024",
        ExtraworkDayRequest: "Mobi.033",
        ExtraworkDayApprove: "Mobi.034",
    },

    VALUE: {
        ID: "ID",
        Name: "Name",
        Name1: "Name1",
        PageSize: 20,
        PageIndex: 0
    },

    HrmProvider: {
        Alert: "Alert",
        Top: "Top",
        Bottom: "Bottom"
    },

    SecureStore: {
        UserPassword: 'LV_119212931110212962214119',
        IsAutoLogin: 'LV_IsAutoLogin'
    }
}

export default CommonConst;