/* eslint-disable max-len */
/* eslint-disable @typescript-eslint/quotes */
/* eslint-disable @typescript-eslint/naming-convention */
const HrmAPIConst = {
    SYSTEM: {
        Alias_GetValueList: "HrmMobileApp/System/GetValueList",
        GetValueList: "GetValueList",
        Alias_GetCombobox: "HrmMobileApp/System/GetCombobox",
        GetCombobox: "GetCombobox",
        Alias_UpdateEmployeeFilter: "HrmMobileApp/Employee/UpdateEmployeeFilter",
        UpdateEmployeeFilter: "UpdateEmployeeFilter",
        Alias_GetDataError: "HrmMobileApp/System/GetDataError",
        GetDataError: "GetDataError",
    },
    APPROVE_REGISTRATION: {
        Alias_ApproveRegistrationForm: "HrmMobileApp/CnB/Notification/ApproveRegistrationForm",
        ApproveRegistrationForm: "ApproveRegistrationForm"
    },
    LEAVE_REQUEST: {
        Alias_GetLeaveRequestAndDataRemainLeaveNumber: "HrmMobileApp/CnB/LeaveRequest/GetLeaveRequestAndDataRemainLeaveNumber",
        GetLeaveRequestAndDataRemainLeaveNumber: "GetLeaveRequestAndDataRemainLeaveNumber",
        Alias_GetLeaveRequest: "HrmMobileApp/CnB/LeaveRequest/GetLeaveRequest",
        GetLeaveRequest: "GetLeaveRequest",
        Alias_GetListKows: "HrmMobileApp/CnB/LeaveRequest/GetListKows",
        GetListKows: "GetListKows",
        Alias_CreateLeaveRequest: "HrmMobileApp/CnB/LeaveRequest/CreateLeaveRequest",
        CreateLeaveRequest: "CreateLeaveRequest",
        Alias_CalFnSendMailRejectRegLeave: "HrmMobileApp/CnB/LeaveApprove/CalFnSendMailRejectRegLeave",
        CalFnSendMailRejectRegLeave: "CalFnSendMailRejectRegLeave"
    },
    BUSINESS_TRIP: {
        Alias_GetBusinessTripRequest: "HrmMobileApp/CnB/BusinessTripRequest/GetBusinessTripRequest",
        GetBusinessTripRequest: "GetBusinessTripRequest",
        Alias_CreateBusinessTripRequest: "HrmMobileApp/CnB/BusinessTripRequest/CreateBusinessTripRequest",
        CreateBusinessTripRequest: "CreateBusinessTripRequest",
        Alias_GetConfigBusinessTrip: "HrmMobileApp/CnB/BusinessTripRequest/GetConfigBusinessTrip",
        GetConfigBusinessTrip: "GetConfigBusinessTrip",
        Alias_GetBusinessTripApproveLazyLoad: "HrmMobileApp/CnB/BusinessTripRequest/GetBusinessTripApproveLazyLoad",
        GetBusinessTripApproveLazyLoad: "GetBusinessTripApproveLazyLoad",
        Alias_SendRequestBusinessTripRequest: "HrmMobileApp/CnB/BusinessTripRequest/SendRequestBusinessTripRequest",
        SendRequestBusinessTripRequest: "SendRequestBusinessTripRequest",
        Alias_RejectRequestBusinessTripRequest: "HrmMobileApp/CnB/BusinessTripRequest/RejectRequestBusinessTripRequest",
        RejectRequestBusinessTripRequest: "RejectRequestBusinessTripRequest",
        Alias_GetBusinessTripApprove: "HrmMobileApp/CnB/BusinessTripRequest/GetBusinessTripApprove",
        GetBusinessTripApprove: "GetBusinessTripApprove",
        Alias_UpdateBusinessTripApprover: "HrmMobileApp/CnB/BusinessTripRequest/UpdateBusinessTripApprover",
        UpdateBusinessTripApprover: "UpdateBusinessTripApprover",
        Alias_UpdateEmployeeFilter: "HrmMobileApp/CnB/BusinessTripRequest/UpdateEmployeeFilter",
        UpdateEmployeeFilter: "UpdateEmployeeFilter",
        Alias_GetListEmployee: "HrmMobileApp/CnB/BusinessTripRequest/GetListEmployee",
        GetListEmployee: "GetListEmployee",
        Alias_UploadFile: "HrmMobileApp/CnB/Export/UploadFile",
        UploadFile: "UploadFile",
        Alias_CheckFileUpload: "HrmMobileApp/CnB/Export/CheckFileUpload",
        CheckFileUpload: "CheckFileUpload",
        Alias_DeleteEmployeeBusinessTrip: "HrmMobileApp/CnB/BusinessTripRequest/DeleteEmployeeBusinessTrip",
        DeleteEmployeeBusinessTrip: "DeleteEmployeeBusinessTrip",
        Alias_GetListEmployeeLazyLoad: "HrmMobileApp/CnB/BusinessTripRequest/GetListEmployeeLazyLoad",
        GetListEmployeeLazyLoad: "GetListEmployeeLazyLoad",

        Alias_GetEndDateFromNumDay: "HrmMobileApp/CnB/BusinessTripRequest/GetEndDateFromNumDay",
        Alias_GetEndDateFromNumDay_Leave: "HrmMobileApp/CnB/BusinessTripRequest/GetEndDateFromNumDay_Leave",
        GetEndDateFromNumDay: "GetEndDateFromNumDay",
        GetEndDateFromNumDay_Leave: "GetEndDateFromNumDay_Leave",
        Alias_GetDayNumWithLeavePeriod: "HrmMobileApp/CnB/BusinessTripRequest/GetDayNumWithLeavePeriod",
        GetDayNumWithLeavePeriod: "GetDayNumWithLeavePeriod",
    },
    LEAVE_APPROVE: {
        Alias_GetLeaveApprove: "HrmMobileApp/CnB/LeaveApprove/GetLeaveApprove",
        GetLeaveApprove: "GetLeaveApprove",
        Alias_GetLeaveApproveLazyLoad: "HrmMobileApp/CnB/LeaveApprove/GetLeaveApproveLazyLoad",
        GetLeaveApproveLazyLoad: "GetLeaveApproveLazyLoad",
        Alias_ApproveLeaveRequest: "HrmMobileApp/CnB/LeaveApprove/ApproveLeaveRequest",
        ApproveLeaveRequest: "ApproveLeaveRequest"
    },
    OT_REQUEST: {
        Alias_GetOTRequestConfig: "HrmMobileApp/CnB/OTRequest/GetOTRequestConfig",
        GetOTRequestConfig: "GetOTRequestConfig",
        Alias_GetOTRequest: "HrmMobileApp/CnB/OTRequest/GetOTRequest",
        GetOTRequest: "GetOTRequest",
        Alias_CreateOTRequest: "HrmMobileApp/CnB/OTRequest/CreateOTRequest",
        CreateOTRequest: "CreateOTRequest",
        Alias_CalFnSendMailRejectOT: "HrmMobileApp/CnB/OTRequest/CalFnSendMailRejectOT",
        CalFnSendMailRejectOT: "CalFnSendMailRejectOT"
    },
    OT_APPROVE: {
        Alias_GetOTApprove: "HrmMobileApp/CnB/OTApprove/GetOTApprove",
        GetOTApprove: "GetOTApprove",
        Alias_GetOTApproveLazyLoad: "HrmMobileApp/CnB/OTApprove/GetOTApproveLazyLoad",
        GetOTApproveLazyLoad: "GetOTApproveLazyLoad",
        Alias_ApproveOTRequest: "HrmMobileApp/CnB/OTApprove/ApproveOTRequest",
        ApproveOTRequest: "ApproveOTRequest"
    },
    OT_GROUP_REQUEST: {
        Alias_GetOTGroupRequest: "HrmMobileApp/CnB/OTGroupRequest/GetOTGroupRequest",
        GetOTGroupRequest: "GetOTGroupRequest",
        Alias_GetConfigOTGroup: "HrmMobileApp/CnB/OTGroupRequest/GetConfigOTGroup",
        GetConfigOTGroup: "GetConfigOTGroup",
        Alias_SendRequestOTGroupRequest: "HrmMobileApp/CnB/OTGroupRequest/SendRequestOTGroupRequest",
        SendRequestOTGroupRequest: "SendRequestOTGroupRequest",
        Alias_RejectRequestOTGroupRequest: "HrmMobileApp/CnB/OTGroupRequest/RejectRequestOTGroupRequest",
        RejectRequestOTGroupRequest: "RejectRequestOTGroupRequest",
        Alias_GetOTGroupApprove: "HrmMobileApp/CnB/OTGroupRequest/GetOTGroupApprove",
        GetOTGroupApprove: "GetOTGroupApprove",
        Alias_GetOTGroupApproveLazyLoad: "HrmMobileApp/CnB/OTGroupRequest/GetOTGroupApproveLazyLoad",
        GetOTGroupApproveLazyLoad: "GetOTGroupApproveLazyLoad",
        Alias_UpdateOTGroupApprover: "HrmMobileApp/CnB/OTGroupRequest/UpdateOTGroupApprover",
        UpdateOTGroupApprover: "UpdateOTGroupApprover",
        Alias_UpdateEmployeeFilter: "HrmMobileApp/CnB/OTGroupRequest/UpdateEmployeeFilter",
        UpdateEmployeeFilter: "UpdateEmployeeFilter",
        Alias_GetListEmployee: "HrmMobileApp/CnB/OTGroupRequest/GetListEmployee",
        GetListEmployee: "GetListEmployee",
        Alias_DeleteEmployeeOTGroup: "HrmMobileApp/CnB/OTGroupRequest/DeleteEmployeeOTGroup",
        DeleteEmployeeOTGroup: "DeleteEmployeeOTGroup",
        Alias_GetListEmployeeLazyLoad: "HrmMobileApp/CnB/OTGroupRequest/GetListEmployeeLazyLoad",
        GetListEmployeeLazyLoad: "GetListEmployeeLazyLoad",
        Alias_SaveIsPayOTGroup: "HrmMobileApp/CnB/OTGroupRequest/SaveIsPayOTGroup",
        SaveIsPayOTGroup: "OTGroupRequest",

    },
    OT_GROUP_APPROVE: {

    },
    MYPROFILE: {
        GetEmpInfoProfile: "HrmMobileApp/CnB/Profile/GetEmpInfoProfile",
        GetConfigField: "HrmMobileApp/CnB/Profile/GetConfigField",
        GetListEmpAllowance:'HrmMobileApp/CnB/Profile/GetListEmpAllowance'
    },
    EMPLOYEE: {
        GetBasicProfile: "HrmMobileApp/CnB/Profile/GetBasicProfile",
        GetListEmpByManage: "HrmMobileApp/CnB/Profile/GetListEmpByManage",
        GetEmpDirectory: "HrmMobileApp/CnB/EmployeeDirectory/GetEmpDirectory",
        GetEmpCodeByQR: "HrmMobileApp/CnB/EmployeeDirectory/SearchEmployeeByQRCode",
        GetListEmployeeForManagerCode: "GetListEmployeeForManagerCode",
        Alias_GetListEmployeeForManagerCode: "HrmMobileApp/Employee/GetListEmployeeForManagerCode",
        GetDepartmentTreeByUserID: "GetDepartmentTreeByUserID",
        Alias_GetDepartmentTreeByUserID: "HrmMobileApp/Employee/GetDepartmentTreeByUserID",
        GetDepartmentTree: "GetDepartmentTree",
        Alias_GetDepartmentTree: "HrmMobileApp/Employee/GetDepartmentTree",
        GetEmpDirectoryForManager: "GetEmpDirectoryForManager",
        Alias_GetEmpDirectoryForManager: "HrmMobileApp/CnB/EmployeeDirectory/GetEmpDirectoryForManager",
        GetConfigEmployeeDirectorys: "GetConfigEmployeeDirectorys",
        Alias_GetConfigEmployeeDirectorys: "HrmMobileApp/CnB/EmployeeDirectory/GetConfigEmployeeDirectorys",
        GetFileFunc: "GetFileFunc",
        Alias_GetFileFunc: "HrmMobileApp/Employee/GetFileFunc",
        GenGuid: "GenGuid",
        Alias_GenGuid: "HrmMobileApp/Employee/GenGuid",
        UploadFile: "UploadFile",
        Alias_UploadFile: "HrmMobileApp/Employee/UploadFile",
        DeleteFile: "DeleteFile",
        Alias_GetEmpActive: "HrmMobileApp/Employee/GetEmpActive",
        GetEmpActive: "GetEmpActive",
        Alias_DeleteFile: "HrmMobileApp/Employee/DeleteFile",
    },
    EMPLOYEEDIRECTORY: {
        GetDepartmentTreeForDirectorys: "GetDepartmentTreeForDirectorys",
        Alias_GetDepartmentTreeForDirectorys: "HrmMobileApp/CnB/EmployeeDirectory/GetDepartmentTreeForDirectorys",
    },
    MYTEAM: {
        GetMyTeam: "HrmMobileApp/CnB/Team/GetMyTeams",
        Alias_GetListDirectManager: "HrmMobileApp/CnB/Team/GetListDirectManager",
        GetListDirectManager: "GetListDirectManager",
        Alias_GetListInDirectManager: "HrmMobileApp/CnB/Team/GetListInDirectManager",
        GetListInDirectManager: "GetListInDirectManager",
    },
    LOGIN: {
        ValidateOTP: "core/authentication/ValidateOTP",
        Login: "core/authentication/login",
        SendMailOTP: "core/authentication/SendMailOTP",
        GetConfigMobile: "HrmMobileApp/ConfigMobile/GetConfigMobile",
        Alias_GenMobileUsers: "HrmMobileApp/CnB/ConfigMobile/GenMobileUsers",
        GenMobileUsers: "GenMobileUsers",
        Alias_ChangeLanguage: "core/authentication/ChangeLanguage",
        ChangeLanguage: "ChangeLanguage",
        SubmitSocialData: "core/authentication/SubmitSocialData",
        Alias_GetConfigLogin: "HrmMobileApp/ConfigMobile/GetConfigLogin",
        GetConfigLogin: "GetConfigLogin",
        LoginAzure:"core/authentication/loginazure",
        SubmitSocialData:"core/authentication/SubmitSocialData",
    },
    HOMEPAGE: {
        Logout: "core/authentication/logout",
        FunctionList: "HrmMobileApp/core/HomePage/FunctionList",
        ForApple_FunctionList: "HrmMobileApp/core/HomePage/ForApple_FunctionList",
        BasicProfile: "HrmMobileApp/CnB/Profile/GetBasicProfile",
        CheckSession: "core/authentication/checkLogin",
        ClearTokenByUser: "HrmMobileApp/core/HomePage/ClearTokenByUser",
        ClearTokenByPhone: "HrmMobileApp/core/HomePage/ClearTokenByPhone",
        Alias_GetSceneKey: "HrmMobileApp/ConfigMobile/GetSceneKey",
        GetSceneKey: "GetSceneKey",
        GetCountFunctionList: "HrmMobileApp/core/HomePage/GetCountFunctionList",
        Alias_GetSettingForCustomer: "HrmMobileApp/core/HomePage/GetSettingForCustomer",
        GetSettingForCustomer: "GetSettingForCustomer"
    },
    CHECKINOUT: {
        Alias_GetFirstInLastOut: "HrmMobileApp/CnB/CheckInOut/GetFirstInLastOut",
        GetFirstInLastOut: "GetFirstInLastOut",
        Alias_CheckInOut: "HrmMobileApp/CnB/CheckInOut/CheckInOut",
        CheckInOut: "CheckInOut",
        Alias_GetPayrollDow: "HrmMobileApp/CnB/CheckInOut/GetPayrollDow",
        GetPayrollDow: "GetPayrollDow",
        Alias_GetFromToDateFnScanCode: "HrmMobileApp/CnB/CheckInOut/GetFromToDateFnScanCode",
        GetFromToDateFnScanCode: "GetFromToDateFnScanCode",
        Alias_GetHistoryCheckInOutInDay: "HrmMobileApp/CnB/CheckInOut/GetHistoryCheckInOutInDay",
        GetHistoryCheckInOutInDay: "GetHistoryCheckInOutInDay",
        Alias_GetUserGPSActivityLogs: "HrmMobileApp/CnB/CheckInOut/GetUserGPSActivityLogs",
        GetUserGPSActivityLogs: "GetUserGPSActivityLogs",
        Alias_GetDateTime: "HrmMobileApp/CnB/CheckInOut/GetDateTime",
        GetDateTime: "GetDateTime",
        Alias_AuditEventCheckInOut: "HrmMobileApp/CnB/CheckInOut/AuditEventCheckInOut",
        AuditEventCheckInOut: "AuditEventCheckInOut",
    },
    CHANGEPASSWORD: {
        Alias_ChangePassword: "HrmMobileApp/User/ChangePassword",
        ChangePassword: "ChangePassword",
    },
    MYTIMESHEET: {
        Alias_GetTimeSheet: "HrmMobileApp/CnB/Timesheet/GetTimeSheet",
        GetTimeSheet: "GetTimeSheet",
        Alias_GetTimeSheetConfig: "HrmMobileApp/CnB/Timesheet/GetTimeSheetConfig",
        GetTimeSheetConfig: "GetTimeSheetConfig",
        Alias_GetListLeave: "HrmMobileApp/CnB/Timesheet/GetListLeave",
        GetListLeave: "GetListLeave",
        Alias_GetListOT: "HrmMobileApp/CnB/Timesheet/GetListOT",
        GetListOT: "GetListOT",
        Alias_GetListBusinessTrip: "HrmMobileApp/CnB/Timesheet/GetListBusinessTrip",
        GetListBusinessTrip: "GetListBusinessTrip",
        Alias_GetTimesheetTopThree: "HrmMobileApp/CnB/Timesheet/GetTimesheetTopThree",
        GetTimesheetTopThree: "GetTimesheetTopThree",
    },
    NEWS: {
        GetListNews: "HrmMobileApp/CnB/News/GetListNews",
        GetListNews4Apple: "HrmMobileApp/CnB/News/ForApple_GetListNews",
        GetListTabs: "HrmMobileApp/CnB/News/GetListTabs",
        GetListFiles: "HrmMobileApp/CnB/News/GetListFiles",
        Alias_GetFunctionListPostNew: "HrmMobileApp/CnB/News/GetFunctionListPostNew",
        GetFunctionListPostNew: "GetFunctionListPostNew",
        Alias_CreatePostNew: "HrmMobileApp/CnB/News/CreatePostNew",
        CreatePostNew: "CreatePostNew",
    },
    MISSINGINOUT: {
        Alias_GetMissingInOutRequest: "HrmMobileApp/CnB/MissingInOut/GetMissingInOutRequest",
        GetMissingInOutRequest: "GetMissingInOutRequest",
        Alias_GetPayrollDow: "HrmMobileApp/CnB/MissingInOut/GetPayrollDow",
        GetPayrollDow: "GetPayrollDow",
        Alias_GetScanTimeInfo_forAddNew: "HrmMobileApp/CnB/MissingInOut/GetScanTimeInfo_forAddNew",
        GetScanTimeInfo_forAddNew: "GetScanTimeInfo_forAddNew",
        Alias_SendRequestScanTimeRequest: "HrmMobileApp/CnB/MissingInOut/SendRequestScanTimeRequest",
        SendRequestScanTimeRequest: "SendRequestScanTimeRequest",
        Alias_RejectRequestScanTimeRequest: "HrmMobileApp/CnB/MissingInOut/RejectRequestScanTimeRequest",
        RejectRequestScanTimeRequest: "RejectRequestScanTimeRequest",
        Alias_GetMissingInOutApprove: "HrmMobileApp/CnB/MissingInOut/GetMissingInOutApprove",
        GetMissingInOutApprove: "GetMissingInOutApprove",
        Alias_GetMissingInOutApproveLazyLoad: "HrmMobileApp/CnB/MissingInOut/GetMissingInOutApproveLazyLoad",
        GetMissingInOutApproveLazyLoad: "GetMissingInOutApproveLazyLoad",
        Alias_UpdateMissingInOutApprover: "HrmMobileApp/CnB/MissingInOut/UpdateMissingInOutApprover",
        UpdateMissingInOutApprover: "UpdateMissingInOutApprover",
        Alias_ValidateWarningScanTimeRequest: "HrmMobileApp/CnB/MissingInOut/ValidateWarningScanTimeRequest",
        ValidateWarningScanTimeRequest: "ValidateWarningScanTimeRequest",
    },
    MYPAYSTUB: {
        Alias_GetPayrollDow: "HrmMobileApp/CnB/MyPayStub/GetPayrollDow",
        GetPayrollDow: "GetPayrollDow",
        Alias_GetTemplatePaystub: "HrmMobileApp/CnB/MyPayStub/GetTemplatePaystub",
        GetTemplatePaystub: "GetTemplatePaystub",
        Alias_GetPaystubField: "HrmMobileApp/CnB/MyPayStub/GetPaystubField",
        GetPaystubField: "GetPaystubField",
        Alias_GetPaystub: "HrmMobileApp/CnB/MyPayStub/GetPaystub",
        GetPaystub: "GetPaystub",
        Alias_GetTemplateGroupActive: "HrmMobileApp/CnB/MyPayStub/GetTemplateGroupActive",
        GetTemplateGroupActive: "GetTemplateGroupActive",
        Alias_GetTemplateGroupField: "HrmMobileApp/CnB/MyPayStub/GetTemplateGroupField",
        GetTemplateGroupField: "GetTemplateGroupField",
        Alias_GetTemplateGroupFieldDynamic: "HrmMobileApp/CnB/MyPayStub/GetTemplateGroupFieldDynamic",
        GetTemplateGroupFieldDynamic: "GetTemplateGroupFieldDynamic"
    },
    EMPLOYEEATTENDANCE: {
        Alias_GetAttendanceSheet: "HrmMobileApp/CnB/EmployeeAttendance/GetAttendanceSheet",
        GetAttendanceSheet: "GetAttendanceSheet",
        Alias_UpdateAttendanceSheet: "HrmMobileApp/CnB/EmployeeAttendance/UpdateAttendanceSheet",
        UpdateAttendanceSheet: "UpdateAttendanceSheet",
        Alias_SaveAttendanceSheet: "HrmMobileApp/CnB/EmployeeAttendance/SaveAttendanceSheet",
        SaveAttendanceSheet: "SaveAttendanceSheet",
        Alias_GetDataHistory: "HrmMobileApp/CnB/EmployeeAttendance/GetDataHistory",
        GetDataHistory: "GetDataHistory",
        Alias_GetLeaveWithRecordID: "HrmMobileApp/CnB/EmployeeAttendance/GetLeaveWithRecordID",
        GetLeaveWithRecordID: "GetLeaveWithRecordID",
        Alias_GetListAttendanceSheet_tmp: "HrmMobileApp/CnB/EmployeeAttendance/GetListAttendanceSheet_tmp",
        GetListAttendanceSheet_tmp: "GetListAttendanceSheet_tmp",
        Alias_GetBusinessTripWithRecordID: "HrmMobileApp/CnB/EmployeeAttendance/GetBusinessTripWithRecordID",
        GetBusinessTripWithRecordID: "GetBusinessTripWithRecordID",
    },
    LATEEARLY: {
        Alias_GetListKows: "HrmMobileApp/CnB/LateEarly/GetListKows",
        GetListKows: "GetListKows",
        Alias_GetLateEarlyRequest: "HrmMobileApp/CnB/LateEarly/GetLateEarlyRequest",
        GetLateEarlyRequest: "GetLateEarlyRequest",
        Alias_GetlateEarlyInfo_forAddNew: "HrmMobileApp/CnB/LateEarly/GetlateEarlyInfo_forAddNew",
        GetlateEarlyInfo_forAddNew: "GetlateEarlyInfo_forAddNew",
        Alias_SendRequestLateEarlyRequest: "HrmMobileApp/CnB/LateEarly/SendRequestLateEarlyRequest",
        SendRequestLateEarlyRequest: "SendRequestLateEarlyRequest",
        Alias_RejectRequestLateEarlyRequest: "HrmMobileApp/CnB/LateEarly/RejectRequestLateEarlyRequest",
        RejectRequestLateEarlyRequest: "RejectRequestLateEarlyRequest",
        Alias_GetLateEarlyApprove: "HrmMobileApp/CnB/LateEarly/GetLateEarlyApprove",
        GetLateEarlyApprove: "GetLateEarlyApprove",
        Alias_GetLateEarlyApproveLazyLoad: "HrmMobileApp/CnB/LateEarly/GetLateEarlyApproveLazyLoad",
        GetLateEarlyApproveLazyLoad: "GetLateEarlyApproveLazyLoad",
        Alias_UpdateLateEarlyApprover: "HrmMobileApp/CnB/LateEarly/UpdateLateEarlyApprover",
        UpdateLateEarlyApprover: "UpdateLateEarlyApprover",
    },
    EXTRADAYOFF_REQUEST: {
        Alias_GetDataRemainLeaveNumber: "HrmMobileApp/CnB/ExtraDayOffRequest/GetDataRemainLeaveNumber",
        GetDataRemainLeaveNumber: "GetDataRemainLeaveNumber",
        Alias_GetExtraDayOffRequestAndDataRemainLeaveNumber: "HrmMobileApp/CnB/ExtraDayOffRequest/GetExtraDayOffRequestAndDataRemainLeaveNumber",
        GetExtraDayOffRequestAndDataRemainLeaveNumber: "GetExtraDayOffRequestAndDataRemainLeaveNumber",
        Alias_GetListKows: "HrmMobileApp/CnB/ExtraDayOffRequest/GetListKows",
        GetListKows: "GetListKows",
        Alias_CreateExtraDayOffRequest: "HrmMobileApp/CnB/ExtraDayOffRequest/CreateExtraDayOffRequest",
        CreateExtraDayOffRequest: "CreateExtraDayOffRequest",
        Alias_GetListExtraDayOffRequest: "HrmMobileApp/CnB/ExtraDayOffRequest/GetListExtraDayOffRequest",
        GetListExtraDayOffRequest: "GetListExtraDayOffRequest",
        Alias_CalFnSendMailRejectRegLeave: "HrmMobileApp/CnB/ExtraDayOffApprove/CalFnSendMailRejectRegLeave",
        CalFnSendMailRejectRegLeave: "CalFnSendMailRejectRegLeave",
        Alias_GetConfigCustomerDayNum: "HrmMobileApp/CnB/ExtraDayOffApprove/GetConfigCustomerDayNum",
        GetConfigCustomerDayNum: "GetConfigCustomerDayNum",
        Alias_GetToDate: "HrmMobileApp/CnB/ExtraDayOffApprove/GetToDate",
        GetToDate: "GetToDate"


    },
    EXTRADAYOFF_APPROVE: {
        Alias_GetLeaveApprove: "HrmMobileApp/CnB/ExtraDayOffApprove/GetLeaveApprove",
        GetLeaveApprove: "GetLeaveApprove",
        Alias_GetLeaveApproveLazyLoad: "HrmMobileApp/CnB/ExtraDayOffApprove/GetLeaveApproveLazyLoad",
        GetLeaveApproveLazyLoad: "GetLeaveApproveLazyLoad",
        Alias_ApproveExtraDayOffRequest: "HrmMobileApp/CnB/ExtraDayOffApprove/ApproveExtraDayOffRequest",
        ApproveExtraDayOffRequest: "ApproveExtraDayOffRequest",
    },
    QA: {
        Alias_GetQATopic: "HrmMobileApp/CnB/QuestionAndAnswer/GetQATopic",
        GetQATopic: "GetQATopic",
        Alias_GetMyPost: "HrmMobileApp/CnB/QuestionAndAnswer/GetMyPost",
        GetMyPost: "GetMyPost",
        Alias_GetReply: "HrmMobileApp/CnB/QuestionAndAnswer/GetReply",
        GetReply: "GetReply",
        Alias_GetMyAnswer: "HrmMobileApp/CnB/QuestionAndAnswer/GetMyAnswer",
        GetMyAnswer: "GetMyAnswer",

        Alias_SendAnswer: "HrmMobileApp/CnB/QuestionAndAnswer/PostAnswer", //Tra loi, comment
        SendAnswer: "PostAnswer",
        Alias_ReViewAnswer: "HrmMobileApp/CnB/QuestionAndAnswer/ReViewAnswer",
        ReViewAnswer: "ReViewAnswer",
        Alias_PostQuestion: "HrmMobileApp/CnB/QuestionAndAnswer/PostQuestion", // Dat cau hoi
        PostQuestion: "PostQuestion",

        Alias_UpdateSatus: "HrmMobileApp/CnB/QuestionAndAnswer/UpdateSatus",
        UpdateSatus: "UpdateSatus",
        Alias_UpdateSatusAll: "HrmMobileApp/CnB/QuestionAndAnswer/UpdateSatusAll",
        UpdateSatusAll: "UpdateSatusAll"
    },
    REPORT: {
        Alias_GetConfigReport: "HrmMobileApp/CnB/Report/GetConfigReport",
        GetConfigReport: "GetConfigReport",
        Alias_GetDataThongKeTuyenMoi: "HrmMobileApp/CnB/Report/GetDataThongKeTuyenMoi",
        GetDataThongKeTuyenMoi: "GetDataThongKeTuyenMoi",
        Alias_GetDataThongKeTuyenMoi_getEmpDetail: "HrmMobileApp/CnB/Report/GetDataThongKeTuyenMoi_getEmpDetail",
        GetDataThongKeTuyenMoi_getEmpDetail: "GetDataThongKeTuyenMoi_getEmpDetail",
        Alias_GetDataThongKeHienCo: "HrmMobileApp/CnB/Report/GetDataThongKeHienCo",
        GetDataThongKeHienCo: "GetDataThongKeHienCo",
        Alias_GetDataThongKeHienCo_getEmpDetail: "HrmMobileApp/CnB/Report/GetDataThongKeHienCo_getEmpDetail",
        GetDataThongKeHienCo_getEmpDetail: "GetDataThongKeHienCo_getEmpDetail",
        Alias_GetDataThongKeVangMat: "HrmMobileApp/CnB/Report/GetDataThongKeVangMat",
        GetDataThongKeVangMat: "GetDataThongKeVangMat",
        Alias_GetDataThongKeVangMat_getEmpDetail: "HrmMobileApp/CnB/Report/GetDataThongKeVangMat_getEmpDetail",
        GetDataThongKeVangMat_getEmpDetail: "GetDataThongKeVangMat_getEmpDetail",
        Alias_GetDataThongKeNghiViec: "HrmMobileApp/CnB/Report/GetDataThongKeNghiViec",
        GetDataThongKeNghiViec: "GetDataThongKeNghiViec",
        Alias_GetDataThongKeNghiViec_getEmpDetail: "HrmMobileApp/CnB/Report/GetDataThongKeNghiViec_getEmpDetail",
        GetDataThongKeNghiViec_getEmpDetail: "GetDataThongKeNghiViec_getEmpDetail",
        Alias_GetDataThongKeBoNhiem: "HrmMobileApp/CnB/Report/GetDataThongKeBoNhiem",
        GetDataThongKeBoNhiem: "GetDataThongKeBoNhiem",
        Alias_GetDataThongKeBoNhiem_getEmpDetail: "HrmMobileApp/CnB/Report/GetDataThongKeBoNhiem_getEmpDetail",
        GetDataThongKeBoNhiem_getEmpDetail: "GetDataThongKeBoNhiem_getEmpDetail",
    },
    NOTIFICATION: {
        Alias_GetListNotification: "HrmMobileApp/CnB/Notification/GetListNotification",
        GetListNotification: "GetListNotification",
        Alias_UpdateStatus: "HrmMobileApp/CnB/Notification/UpdateStatus",
        UpdateStatus: "UpdateStatus",
        Alias_UpdateStatusAll: "HrmMobileApp/CnB/Notification/UpdateStatusAll",
        UpdateStatusAll: "UpdateStatus",
        Alias_GetDetailRegistrationForm: "HrmMobileApp/CnB/Notification/GetDetailRegistrationForm",
        GetDetailRegistrationForm: "GetDetailRegistrationForm",
    },
    AUTHORIZATION: {
        Alias_GetConfigApproverSubstitute: "HrmMobileApp/CnB/Authorization/GetConfigApproverSubstitute",
        GetConfigApproverSubstitute: "GetConfigApproverSubstitute",
        Alias_GetApproverSubstitute: "HrmMobileApp/CnB/Authorization/GetApproverSubstitute",
        GetApproverSubstitute: "GetApproverSubstitute",
        Alias_SendApproverSubstitute: "HrmMobileApp/CnB/Authorization/SendApproverSubstitute",
        SendApproverSubstitute: "SendApproverSubstitute",
        Alias_RejectApproverSubstitute: "HrmMobileApp/CnB/Authorization/RejectApproverSubstitute",
        RejectApproverSubstitute: "RejectApproverSubstitute",
    },
    EXTRAWORKDAY_REQUEST: {
        Alias_LoadDefaultRegistPage: "HrmMobileApp/CnB/ExtraWorkDayRequest/LoadDefaultRegistPage",
        LoadDefaultRegistPage: "LoadDefaultRegistPage",
        Alias_LoadDefaultData: "HrmMobileApp/CnB/ExtraWorkDayRequest/LoadDefaultData",
        LoadDefaultData: "LoadDefaultData",
        Alias_GetConfigExtraWorkDay: "HrmMobileApp/CnB/ExtraWorkDayRequest/GetConfigExtraWorkDay",
        GetConfigExtraWorkDay: "GetConfigExtraWorkDay",
        Alias_SendRequestExtraWorkDayRequest: "HrmMobileApp/CnB/ExtraWorkDayRequest/SendRequestExtraWorkDayRequest",
        SendRequestExtraWorkDayRequest: "SendRequestExtraWorkDayRequest",
        Alias_GetListExtraWorkDayRequest: "HrmMobileApp/CnB/ExtraWorkDayRequest/GetListExtraWorkDayRequest",
        GetListExtraWorkDayRequest: "GetListExtraWorkDayRequest",
        Alias_RejectExtraWorkDayRequest: "HrmMobileApp/CnB/ExtraWorkDayRequest/RejectExtraWorkDayRequest",
        RejectExtraWorkDayRequest: "RejectExtraWorkDayRequest",
        Alias_GetExtraWorkDayApprove: "HrmMobileApp/CnB/ExtraWorkDayRequest/GetExtraWorkDayApprove",
        GetExtraWorkDayApprove: "GetExtraWorkDayApprove",
        Alias_GetExtraWorkDayApproveLazyLoad: "HrmMobileApp/CnB/ExtraWorkDayRequest/GetExtraWorkDayApproveLazyLoad",
        GetExtraWorkDayApproveLazyLoad: "GetExtraWorkDayApproveLazyLoad",
        Alias_UpdateExtraWorkDayApprover: "HrmMobileApp/CnB/ExtraWorkDayRequest/UpdateExtraWorkDayApprover",
        UpdateExtraWorkDayApprover: "UpdateExtraWorkDayApprover",
        Alias_GetKowLateEarly: "HrmMobileApp/CnB/ExtraWorkDayRequest/GetKowLateEarly",
        GetKowLateEarly: "GetKowLateEarly",
    }
};

export default HrmAPIConst;
