-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggjNmACu8jIT+Cb8o
qNZlNcl6SbPVrAy8yPRvOZEGBSOgCgYIKoZIzj0DAQehRANCAATB2qVwbimd+5Al
wlHSg/3U2sC3+2J3wMwBd7nt7QnIV1deveK+MN44ZdT81ozkIMjwMVwwXdJnE+Yg
0DsW6KBF
-----END PRIVATE KEY-----