export class UserModel {
  Administrator: boolean;
  EmployeeCode: string;
  EmployeeFullName: string;
  Expire: any;
  FirstChange: boolean;
  IsCBCC: boolean;
  IsDomainAccount: boolean;
  IsEmployeeOnly: boolean;
  IsFirstChange: boolean;
  IsSystem: boolean;
  Jwt: any;
  Language: string;
  ListOfPortal: any;
  LoginTime: any;
  NeverExpire: boolean;
  NumberDecimalSeparator: string;
  NumberGroupSeparator: string;
  OBEmpCode: any;
  PRDateFormat: string;
  PRDecPlaceCoeffSalary: number;
  PRDecPlaceCurrencyForCal: number;
  PRDecPlaceCurrencyForPay: number;
  PRDecPlaceExRate: number;
  PRDecPlaceProduction: number
  SessionID: string;
  SystemAdmin: boolean;
  TokenID: string;
  UserID: string;
  UserName: string;
}
